---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure dependencies are installed (RedHat).
  package:
    name: "{{ svn2git_dependencies }}"
    state: present

- name: Clone Svn2Git from Gitorious.
  git:
    repo: "{{ svn2git_source_repo }}"
    dest: "{{ svn2git_install_path }}/svn2git"
    version: "{{ svn2git_source_version }}"

- name: Build Svn2Git.
  shell: >
    {{ svn2git_qmake_bin_path }} && make
    chdir={{ svn2git_install_path }}/svn2git
    creates={{ svn2git_install_path }}/svn2git/svn-all-fast-export

- name: Add symlink to svn-all-fast-export.
  file:
    src: "{{ svn2git_install_path }}/svn2git/svn-all-fast-export"
    dest: /usr/bin/svn-all-fast-export
    state: link
