---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure dependencies are installed (RedHat).
  yum: "name={{ item }} state=installed"
  with_items:
    - qt
    - qt-devel
    - subversion-devel
    - gcc-c++
  when: ansible_os_family == 'RedHat'

- name: Ensure dependencies are installed (Debian).
  apt: "name={{ item }} state=installed"
  with_items:
    - qt5-default
    - qtbase5-dev
    - libsvn-dev
    - build-essential
  when: ansible_os_family == 'Debian'

- name: Clone Svn2Git from Gitorious.
  git:
    repo: https://gitorious.org/svn2git/svn2git.git
    dest: "{{ svn2git_install_path }}/svn2git"

- name: Build Svn2Git.
  shell: >
    {{ svn2git_qmake_bin_path }} && make
    chdir={{ svn2git_install_path }}/svn2git
    creates={{ svn2git_install_path }}/svn2git/svn-all-fast-export

- name: Add symlink to svn-all-fast-export.
  file:
    src: "{{ svn2git_install_path }}/svn2git/svn-all-fast-export"
    dest: /usr/bin/svn-all-fast-export
    state: link
